import os

import oracledb
from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv())
oracledb.init_oracle_client()

UN = os.environ.get("UN")
PW = os.environ.get("PW")
DSN = os.environ.get("DSN")

if __name__ == "__main__":
    print("Start Creating Table")
    try:
        with oracledb.connect(user=UN, password=PW, dsn=DSN) as conn:
            with conn.cursor() as cursor:
                cursor.execute(f"""
                    CREATE TABLE uploaded_files (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        file_name VARCHAR2(255),
                        file_path VARCHAR2(500),
                        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
                print("uploaded_files table created")
                
                cursor.execute(f"""
                    CREATE TABLE file_contents (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        file_id NUMBER REFERENCES uploaded_files(id),
                        content_type VARCHAR2(50),
                        markdown CLOB,
                        summary CLOB,
                        embedding VECTOR(1536),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
                print("file_contents table created")
            conn.commit()
            print("End Creating Table")
    except Exception as e:
        print("Error create_table:", e)