import os

import oracledb
from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv())
oracledb.init_oracle_client()

UN = os.environ.get("UN")
PW = os.environ.get("PW")
DSN = os.environ.get("DSN")

if __name__ == "__main__":
    print("Start Creating Table")
    try:
        with oracledb.connect(user=UN, password=PW, dsn=DSN) as conn:
            with conn.cursor() as cursor:
                # cursor.execute(f"""
                #     CREATE TABLE uploaded_files (
                #         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                #         file_name VARCHAR2(255),
                #         file_path VARCHAR2(500),
                #         uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                #     )
                # """)
                # print("uploaded_files table created")
                
                # # Create docs_content table
                # cursor.execute(f"""
                #     CREATE TABLE docs_contents (
                #         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                #         file_id NUMBER REFERENCES uploaded_files(id),
                #         markdown CLOB,
                #         summary VARCHAR2(10000),
                #         embedding VECTOR(1024),
                #         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                #     )
                # """)
                # print("docs_content table created")
                
                # # Create image_content table
                # cursor.execute(f"""
                #     CREATE TABLE image_contents (
                #         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                #         file_id NUMBER REFERENCES uploaded_files(id),
                #         image_blob BLOB,
                #         image_path VARCHAR2(500),
                #         image_url VARCHAR2(255),
                #         summary VARCHAR2(10000),
                #         embedding VECTOR(1024),
                #         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                #     )
                # """)
                # print("image_content table created")
                
                # cursor.execute("""
                #     CREATE TABLE multimodal_contents (
                #         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                #         name VARCHAR2(255),
                #         summary VARCHAR2(10000),
                #         embedding VECTOR(1024),
                #         image_url VARCHAR2(255),
                #         image_blob BLOB,
                #         content_type VARCHAR2(50),
                #         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                #     )
                # """)
                # print("multimodal_contents table created successfully")
                
                cursor.execute("""
                    CREATE TABLE embedding_contents (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(255),
                        summary VARCHAR2(10000),
                        markdown CLOB,
                        embedding VECTOR(1024),
                        file_path VARCHAR2(255),
                        image_blob BLOB,
                        content_type VARCHAR2(50),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
                print("embedding_contents table created successfully")
                
            conn.commit()
            print("End Creating Table")
    except Exception as e:
        print("Error create_table:", e)